name: Publish to Pypi

on:
  push:
    tags:
      - v*

  workflow_dispatch:
    inputs:
      publish:
        description: "Publish to pypi.org?"
        required: false
        default: 'false'

jobs:
  publish:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Publish to pypi
        uses: ./.github/workflows/actions/publish-to-pypi
        with:
          project-name: json-schema-for-humans
          pypi-token: ${{ secrets.PYPI_TOKEN }}
          pre-release: ${{ github.ref != 'refs/heads/master' }}
          dry-run: ${{ github.ref != 'refs/heads/master' && github.event.inputs.publish != 'true' }}
